@echo off
cd /d "%~dp0"
echo Starting IronClad...
echo 1. Activating Virtual Environment...
call venv\Scripts\activate
echo 2. Starting Server (Backend + Frontend)...
python -m uvicorn api_server:app --host 0.0.0.0 --port 8001 --reload
pause
